### ISSUE TITLE
Now Broken with Windows 11 22H2 Release 2215 

### ISSUE THREAD

**Issue by ice00** [darkguy2008/Switchie#2]
With last Windows 11 22H2 Release 2215 the program stop to works (or at least it seems that the space where there should be the little bar is occupied, but it is transparent)

**Comment by Robbson** [comment]
I had no chance to use it in Windows 11 at all, I don't know exactly if it's related to the 22H2 release. As far as I remember it has to do with those virtual desktop windows where some kind of window class isn't known or something like that. I didn't do much research about the issue because I'm still using Windows 10 for most of the PCs I use daily. But I could have a look again into it if interested.

By the way I don't know if @darkguy2008 is still maintaining the project so I'm primarily working on a fork.

**Comment by ice00** [comment]
Actually I was able to go back to previous Windows 11 release as within the week of installation (a feature I find) and still do this every time the new version is installed by Windows Update!

Working in Windows with multiple desktops without this tools is impossible (e.g I still use this in Linux from 1999...)

**Comment by Robbson** [comment]
Oh dear... well, you could disable the Windows auto updates but that's not a secure option 😲.

But when it comes to working with virtual desktops: you can easily switch your virtual desktops by keyboard or touch gestures. Also the dedicated Windows button can be used even though it's one click more. But of course, it heavily depends on your personal preferences and your screen size. 

I'm using Switchie in a heavily modified version where you don't see a preview of the window arrangements for each virtual desktop but their program icons next to each other like a mini taskbar:

![image](https://github.com/darkguy2008/Switchie/assets/7016181/cbd42236-14c3-4f24-974d-377db9db0710)

That's especially useful on notebooks where you don't have much screen space so you probably use most apps maximized where the preview function is no very useful. But I could easily switch back to the other view if required.

**Comment by ice00** [comment]
In last update of version 23H2, now it works again, so I can close the issue. Thanks

**Comment by ice00** [comment]
I find later that the update silent failed, so it was still running in 21H2! With 23H2 is did not started.

However I resolved by myself by modified the code (in fork)

**Comment by pdeegan** [comment]
Thanks for your work on this @ice00, the app is running in 23H2 for me.  This is the best implementation for desktop switching and productivity in Windows 11!

Running on the system (detailed below) the app freezes frequently (sometimes immediately on start, other times it will run for hours). When it freezes, windows do not move between desktops and desktops do not switch with the app.  Restarting doesn't fix every time and it is unclear whether restarting the computer makes a difference.  It also consumes about 12-18% of the CPU and brings clock up to 4Ghz or more when running vs. 2-4% CPU and 2Ghz processor at idle when the app is not running.   Any suggestions for possible optimizations, cache to clear, or settings that can be used to prevent the app from freezing? 

OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
Processor	13th Gen Intel(R) Core(TM) i9-13900H, 2600 Mhz, 14 Core(s), 20 Logical Processor(s)
Installed Physical Memory (RAM)	96.0 GB
Resolution	3840 x 2400 x 60 hertz
Name	Intel(R) Iris(R) Xe Graphics
Driver Version	31.0.101.5590
Adapter Type	NVIDIA GeForce RTX 4090 Laptop GPU, NVIDIA compatible
Driver Version	31.0.15.3847

**Comment by ice00** [comment]
I did not know the internal working of the app (I just adapted it for running on win 23H2 and add some features using ChatGPT code generation), so why you experiment cpu usage on idle.

I see that when you have a windows program that is frozen (not responding), then the app panels freeze too and you cannot change the virtual screens, unless you use standard windows key shortcut (or attend that the program goes out of freeze state).

**Comment by ice00** [comment]
I have experimented the blocking you talk. I had around 50 open windows in 3 virtual desktop and it blocked. 
I can suspect that the internal structure of the program did not handle well such number of windows miniature opened at the same time
